name = "pulse-worker-ipfs"
main = "src/worker.js"
compatibility_date = "2023-07-17"

# The necessary secrets are:
# - PINATA_API_KEY
# - PINATA_SECRET_API_KEY

# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
